"""initial

Revision ID: 652af82b55c8
Revises: 
Create Date: 2025-07-12 16:41:22.539515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652af82b55c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_role',
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('roleId'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('profileImg', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.roleId'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('activity',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('loginAt', sa.DateTime(), nullable=True),
    sa.Column('logoutAt', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('auth',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('aid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cloths',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('c_title', sa.String(length=120), nullable=False),
    sa.Column('c_description', sa.Text(), nullable=True),
    sa.Column('condition', sa.String(length=120), nullable=True),
    sa.Column('hasSwapped', sa.Boolean(), nullable=True),
    sa.Column('genderSuited', sa.String(length=10), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['styles.sid'], ),
    sa.ForeignKeyConstraint(['tid'], ['types.tid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('cloth_img',
    sa.Column('imgId', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['cloths.cid'], ),
    sa.PrimaryKeyConstraint('imgId')
    )
    op.create_table('swap_requests',
    sa.Column('senderCid', sa.Integer(), nullable=False),
    sa.Column('recieverCid', sa.Integer(), nullable=False),
    sa.Column('senderUid', sa.Integer(), nullable=True),
    sa.Column('recieverUid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('updatedBy', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recieverCid'], ['cloths.cid'], ),
    sa.ForeignKeyConstraint(['recieverUid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['senderCid'], ['cloths.cid'], ),
    sa.ForeignKeyConstraint(['senderUid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('senderCid', 'recieverCid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_requests')
    op.drop_table('cloth_img')
    op.drop_table('cloths')
    op.drop_table('auth')
    op.drop_table('activity')
    op.drop_table('user')
    op.drop_table('user_role')
    op.drop_table('types')
    op.drop_table('styles')
    # ### end Alembic commands ###
